### ISSUE TITLE
Please release the latest code base

### ISSUE THREAD

**Issue by cscalfani** [purescript-contrib/purescript-css#127]
Is there an ETA for the next release. There are a lot of new features in MAIN compared to the latest version, 4.0.0?

**Comment by thomashoneyman** [comment]
Hi @cscalfani! You're right, a lot of new features have arrived in the default branch but haven't been released. These changes are slated for release alongside the 0.14 version of the PureScript compiler. Releases across the `contrib` organization have been frozen in anticipation of the 0.14 release so that they're ready to go right when the compiler is; you'll see that there are also several 0.14-related breaking changes in the main branch at the moment.

We could have done a better job making a release with non-breaking changes before making breaking 0.14 updates. That ship has sailed, however, and the next release of this library will coincide with PureScript 0.14 (sometime soon).

**Comment by cscalfani** [comment]
You're right, non-breaking releases before a lockdown would be a great idea. Perhaps before the next release.

Thanks for the explanation. Looking forward to 0.14. Not looking forward to the breaking changes. Hopefully, they will be few and far between.

**Comment by thomashoneyman** [comment]
Fortunately the breaking changes are relatively few. However, because core libraries like `prelude` were affected, everything down the line must also have a breaking change to accommodate SemVer (including `css` -- you shouldn't have any problems updating this library).

**Comment by thomashoneyman** [comment]
v5.0.0 is out!
